// <auto-generated />
namespace ExpressMapper.Tests.Projections.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddFlattening : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFlattening));
        
        string IMigrationMetadata.Id
        {
            get { return "201603220950395_AddFlattening"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
